services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    container_name: zookeeper_aula_kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - app-network

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    container_name: kafka_aula
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"      # Externo
      - "29092:29092"    # Interno
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE: "true"
      KAFKA_BROKER: "kafka:29092"
    networks:
      - app-network

  kowl:
    image: quay.io/cloudhut/kowl:latest
    container_name: kowl_aula_kafka
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      - KAFKA_BROKERS=kafka:29092
    networks:
      - app-network

networks:
  app-network:
    driver: bridge